server:
  port: 9001
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/image_cloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  # 使用qq邮箱自动放送邮件
  mail:
    username: 1663956443@qq.com # 发送方邮箱
    password: hrtkszidpvgxdebc  # 授权码
    host: smtp.qq.com  # qq邮件服务地址
    port: 465 # 端口
    default-encoding: utf-8 # 编码格式
    properties: # 其它参数
      mail:
        transport:
          protool: smtp
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          port: ${spring.mail.port}
          auth: true
          starttls:
            enable: true
            required: true

  # redis缓存
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1  # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:   # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10  # 连接池中的最大空闲连接
        min-idle: 0   # 连接池中的最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

      insert-strategy: not_empty  # 插入时，字段为空则不插入
      update-strategy: not_empty  # 更新时，字段为空则不更新

# 外部访问地址（网址、域名或ip地址）
url: http://127.0.0.1:${server.port}

# 文件上传
file:
  uploadFolder: F:/image/ # 文件上传地址
  staticAccessPath: /images/** # 上传的静态资源对外暴露的访问路径
  staticAccessUrlPrefix: ${url}${server.servlet.context-path}/images/ # 外部访问上传的静态资源时的前缀

  maxFileSize: 5MB # 单个文件最大大小
  maxRequestSize: 120MB # 单次请求最大大小

# 雪花算法
snow-flake:
  datacenterId: 1 # 机房id
  workerId: 2 # 机器id
